[package]
name = "NimatronRust"
version = "0.1.0"
authors = ["Sarvarian <Sarvarian@Hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
